services:
  api:
    build:
      dockerfile: docker/api.dockerfile
      context: .
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"

    command: uvicorn app:app --host=0.0.0.0 --port 8000

  frontend:
    build:
      dockerfile: docker/react.dockerfile
      context: .
    volumes:
      - ./react/src:/app/src
      - ./react/index.html:/app/index.html
      - ./react/vite.config.js:/app/vite.config.js

    ports:
     - "3000:3000"

    command: npm run dev 
